image:
  repository: intellistore-api
  tag: latest
  pullPolicy: IfNotPresent

replicas: 2

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

env:
  VAULT_ADDR: "http://vault:8200"
  JWT_SECRET_PATH: "vault://intellistore/keys/jwt-signing-key"
  KAFKA_BROKERS: "kafka-0:9092,kafka-1:9092,kafka-2:9092"
  RAFT_LEADER_ADDR: "raft-metadata-0.raft-metadata.svc.cluster.local:5000"
  LOG_LEVEL: "INFO"

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: api.intellistore.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

podDisruptionBudget:
  enabled: true
  minAvailable: 1

serviceMonitor:
  enabled: true
  interval: 30s
  path: /metrics